// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZxBY5ZvOmwWgTw3Dx3OBa00tlb7kobJs',
    appId: '1:393969183829:web:e1cbefac0b791d5838f8dc',
    messagingSenderId: '393969183829',
    projectId: 'finance-manager-ca7d8',
    authDomain: 'finance-manager-ca7d8.firebaseapp.com',
    storageBucket: 'finance-manager-ca7d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0LBCYzKcfAQwNFTeQpA3nan6GWR0WhxI',
    appId: '1:393969183829:android:812b240b7b23d9e238f8dc',
    messagingSenderId: '393969183829',
    projectId: 'finance-manager-ca7d8',
    storageBucket: 'finance-manager-ca7d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFdyCzaHygNs2dqzVm9dSDoR-akcztJk',
    appId: '1:393969183829:ios:6ba3cc9190adbc6438f8dc',
    messagingSenderId: '393969183829',
    projectId: 'finance-manager-ca7d8',
    storageBucket: 'finance-manager-ca7d8.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );
}
